spring:
  # 数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.192.49.72:3306/project-authority?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowMultiQueries=true&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: Qwz#1201

qinweizhao:
  jwt:
    header: Authorization
    #7天，秒单位
    expire: 604800
    secret: ji8n3439n439n43ld9ne9343fdfer49h


#logging:
#  level:
#    root:
#      debug
